# Header
menu:
  Home: ' ' #otherwise this becomes absolute url and breaks :root
  Archives: archives
rss: /atom.xml

# person image
person_image: images/person.jpg

# Content
excerpt_link: Read More

# Sidebar
widgets:
- recent_posts
- category
- tag

# Miscellaneous
google_analytics: UA-36958710-1
favicon:
linkedin: https://lt.linkedin.com/in/mbardauskas
github: https://github.com/mbardauskas
twitter: https://twitter.com/mbardauskas