# Header
menu:
  Home: ' ' #otherwise this becomes absolute url and breaks :root
  Archives: archives
rss: /atom.xml

# Content
excerpt_link: Read More

# Sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon:
linkedin: http://www.linkedin.com
github: http://www.github.com
twitter: http://www.twitter.com