# Header
menu:
  Home: ' ' #otherwise this becomes absolute url and breaks :root
  Archives: archives
rss: /atom.xml

# person image
person_image: images/person.jpg

# Content
excerpt_link: Read More

# Sidebar
widgets:
- recent_posts
- category
- tag

# Miscellaneous
google_analytics:
favicon:
linkedin: http://www.linkedin.com
github: http://www.github.com
twitter: http://www.twitter.com